FROM node:20

WORKDIR /app

RUN apt-get update && apt-get install -y python3 make g++

COPY package*.json ./

RUN npm install --force

#COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
